### ISSUE TITLE
Game Crash | Looper Block

### ISSUE THREAD

**Issue by akaimusic21** [StavWasPlayZ/Even-More-Instruments#11] opened 2024-07-24 17:23 UTC
Upon placing the Looper Block in a world the game crashes.
1. Install the mod.
2. Open a world.
3. Place the "Looper" in a world.
4. Game will crash.
Ex. Upon re-entering the world, the game will crash. So you need to remove the mod to re-enter the world.

## Game:
Minecraft 1.20.4 with Fabric Loader 0.15.11
## System:
Windows 11 23H2
AMD Ryzen 7 5000 Series + Radeon Graphics

[crash-2024-07-24_13.06.04-server.txt](https://github.com/user-attachments/files/16365476/crash-2024-07-24_13.06.04-server.txt)

**Comment by StavWasPlayZ** [comment] 2024-08-02 18:31
Duplicate of #10

Will be fixed in v6.1

Sorry for the inconvenience!

**Closed by StavWasPlayZ** 2024-08-02 18:31 UTC
Labels: bug
